version: 2.1
orbs:
  cypress: cypress-io/cypress@2
workflows:
  build:
    jobs:
      - cypress/install:
          yarn: true
          executor: cypress/base-14
      - cypress/run:
          requires:
            - cypress/install
          executor: cypress/base-14
          record: true
          parallel: true
          parallelism: 4
          store_artifacts: true
          post-steps:
            - run: yarn test:unit
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: coverage
            # print code coverage summary to the terminal
            - run: ./node_modules/.bin/nyc report
            # send coverage to Codecov
            - run: ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/codecov --pipe
